### PR TITLE
Feature: Environment Variables

### PR DESCRIPTION
**Pull request by axrs**
After: https://github.com/jcowgar/smart_arg/pull/22

### CODE REVIEW

**Comment by jcowgar** [comment]
@axrs, sorry, seems this one has a conflict.

**Comment by axrs** [comment]
@jcowgar No worries. All resolved.

**Comment by jcowgar** [comment]
Thanks for your contributions! They are greatly welcomed!

**Comment by axrs** [comment]
> Thanks for your contributions! They are greatly welcomed!

No Problem. I have a few more enhancements I'm tinkering with. I'll be sure to open PRs as I finalize them.

**Comment by jcowgar** [comment]
@axrs, can you take a peek at master? Seems that tests are failing now for some reason centered around environment parsing. Not sure how I missed this initially when running tests.

`
❯ dart test
00:00 +47 -1: test/smart_arg/smart_arg_test.dart: argument parsing/assignment environment value default value exists if no value found in environment [E]
  Reflecting on un-marked type "TestWithEnvironmentValue"
  package:reflectable/src/reflectable_builder_based.dart 225:9    new _InstanceMirrorImpl
  package:reflectable/src/reflectable_builder_based.dart 2554:12  ReflectableImpl.reflect
  package:smart_arg/src/smart_arg.dart 61:40                      new SmartArg
  test/smart_arg/smart_arg_test.dart                              new TestWithEnvironmentValue
  test/smart_arg/smart_arg_test.dart 369:22                       main.<fn>.<fn>.<fn>

00:00 +47 -1: loading test/smart_arg/smart_arg_test.dart
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
00:00 +47 -2: test/smart_arg/smart_arg_test.dart: argument parsing/assignment environment value environment variable supplied overrides default value [E]
  Reflecting on un-marked type "TestWithEnvironmentValue"
  package:reflectable/src/reflectable_builder_based.dart 225:9    new _InstanceMirrorImpl
  package:reflectable/src/reflectable_builder_based.dart 2554:12  ReflectableImpl.reflect
  package:smart_arg/src/smart_arg.dart 61:40                      new SmartArg
  test/smart_arg/smart_arg_test.dart                              new TestWithEnvironmentValue
  test/smart_arg/smart_arg_test.dart 376:22                       main.<fn>.<fn>.<fn>

00:00 +47 -2: loading test/smart_arg/smart_arg_test.dart
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
00:00 +47 -3: test/smart_arg/smart_arg_test.dart: argument parsing/assignment environment value value supplied overrides environment value [E]
  Reflecting on un-marked type "TestWithEnvironmentValue"
  package:reflectable/src/reflectable_builder_based.dart 225:9    new _InstanceMirrorImpl
  package:reflectable/src/reflectable_builder_based.dart 2554:12  ReflectableImpl.reflect
  package:smart_arg/src/smart_arg.dart 61:40                      new SmartArg
  test/smart_arg/smart_arg_test.dart                              new TestWithEnvironmentValue
  test/smart_arg/smart_arg_test.dart 383:22                       main.<fn>.<fn>.<fn>

00:00 +47 -3: loading test/smart_arg/smart_arg_test.dart
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
00:00 +139 -4: test/smart_arg_test.dart: argument parsing/assignment environment value default value exists if no value found in environment [E]
  Reflecting on un-marked type "TestWithEnvironmentValue"
  package:reflectable/src/reflectable_builder_based.dart 225:9    new _InstanceMirrorImpl
  package:reflectable/src/reflectable_builder_based.dart 2554:12  ReflectableImpl.reflect
  package:smart_arg/src/smart_arg.dart 61:40                      new SmartArg
  test/smart_arg/smart_arg_test.dart                              new TestWithEnvironmentValue
  test/smart_arg/smart_arg_test.dart 369:22                       main.<fn>.<fn>.<fn>

00:00 +139 -4: loading test/smart_arg_test.dart
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
00:00 +139 -5: test/smart_arg_test.dart: argument parsing/assignment environment value environment variable supplied overrides default value [E]
  Reflecting on un-marked type "TestWithEnvironmentValue"
  package:reflectable/src/reflectable_builder_based.dart 225:9    new _InstanceMirrorImpl
  package:reflectable/src/reflectable_builder_based.dart 2554:12  ReflectableImpl.reflect
  package:smart_arg/src/smart_arg.dart 61:40                      new SmartArg
  test/smart_arg/smart_arg_test.dart                              new TestWithEnvironmentValue
  test/smart_arg/smart_arg_test.dart 376:22                       main.<fn>.<fn>.<fn>

00:00 +139 -5: loading test/smart_arg_test.dart
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
00:00 +139 -6: test/smart_arg_test.dart: argument parsing/assignment environment value value supplied overrides environment value [E]
  Reflecting on un-marked type "TestWithEnvironmentValue"
  package:reflectable/src/reflectable_builder_based.dart 225:9    new _InstanceMirrorImpl
  package:reflectable/src/reflectable_builder_based.dart 2554:12  ReflectableImpl.reflect
  package:smart_arg/src/smart_arg.dart 61:40                      new SmartArg
  test/smart_arg/smart_arg_test.dart                              new TestWithEnvironmentValue
  test/smart_arg/smart_arg_test.dart 383:22                       main.<fn>.<fn>.<fn>

00:00 +139 -6: loading test/smart_arg_test.dart
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
00:00 +206 -6: Some tests failed.
`

**Comment by axrs** [comment]
@jcowgar 

I cannot seam to reproduce:

## Windows 10 - Dart 2.15.0-150.0.dev

```
$ dart pub get
$ dart run build_runner build --delete-conflicting-outputs
$ dart test
Building package executable...
Built test:test.
00:02 +212: All tests passed!
```

## Debian Bullseye Slim - Dart 2.14.4

```
$ dart pub get
$ dart run build_runner build --delete-conflicting-outputs
$ dart test
Building package executable... (1.4s)
Built test:test.
00:01 +212: All tests passed!
```

Do you know the environment details/Dart version it was failing in?

**Comment by axrs** [comment]
I think I saw that error when I first wrote the tests. And then remembered I needed to re-run the reflectable builder as I had added new classes with annotations.

**Comment by jcowgar** [comment]
@axrs, oh my that's embarassing, yes, I forgot to rebuild when switching branches :-(

Thanks!

**Comment by axrs** [comment]
No problem :)

**Comment by jcowgar** [comment]
@axrs just ran dart pub publish on it, so 2.0.0 is now on pub.dev. Thanks for these contributions!

**Pull request merged**
